### PR TITLE
Added support for SR clinical data files

### PR DESCRIPTION
**Pull request by bcli4d**
Processing of clinical data files works but I get the error I mentioned in separate email when trying to process other file types. Perhaps I need a different version of dcmqi?

### CODE REVIEW

**Comment by bcli4d** [comment]
Andrey,

I didn't intend to include clientDataScheme.py in my pull request, and you
are welcome to delete it. It is one of those ideas that turned out not to
work.

Regards,
Bill

**Comment by fedorov** [comment]
Bill, I noticed that, but didn't bother to see if it is actually used. I think it is ok to keep it, since I imaging it took effort to put it together, and it is a machine-readable representation of the templates used. So might be useful in the future.

**Comment by bcli4d** [comment]
My intention was certainly to create a machine readable template, though
the result is quite incomplete. OK to keep it I guess.

Do you understand the dcmqi error I encountered? I did download the latest
6/19 build and continue to get that same error. Running on a Mac.

Bill

**Comment by fedorov** [comment]
Bill, if you are talking about this error that you mentioned in one of your emails:

```
/Users/BillClifford/local/builds/dcmqi-mac/bin/tid1500reader
dcmqi repository URL: https://github.com/qiicr/dcmqi.git revision: f621a32 tag: v1.0.4-47-gf621a32
Number of verifying observers: 0
Activity Session: 1
Reference Segment: 1
SourceSeriesForImageSegmentation: 1.3.6.1.4.1.14519.5.2.1.2744.7002.261560220703676715130542397405
TrackingIdentifier: aorta reference region
Backend MacOSX is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/BillClifford/git-home/dcm2tables.test/tabulate.py", line 59, in <module>
    main()
  File "/Users/BillClifford/git-home/dcm2tables.test/tabulate.py", line 37, in main
    dicomParser.parse()
  File "/Users/BillClifford/git-home/dcm2tables.test/DICOMParser.py", line 44, in parse
    self.readMeasurements(measurementsJSON)
  File "/Users/BillClifford/git-home/dcm2tables.test/DICOMParser.py", line 286, in readMeasurements
    value = self.dcm.data_element(attr).value
AttributeError: 'NoneType' object has no attribute 'value'
```

It does not seem to be a dcmqi error. Probably makes sense to investigate what attribute fails and for what specific dataset.

I am working on fixing some other issues in the code, but if you provide more details, I will look into this one later.

**Comment by bcli4d** [comment]
I added print statements to print filename, modality and attr. Here is the
trace:

/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
"/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc
--qt-support --client 127.0.0.1 --port 63096 --file
/Users/BillClifford/git-home/dcm2tables.test/tabulate.py schema.qdbd scratch
pydev debugger: process 36992 is connecting

Connected to pydev debugger (build 163.10154.50)
scratch/scratch/QIN-HEADNECK/QIN-HEADNECK/QIN-HEADNECK-01-0003/1.3.6.1.4.1.14519.5.2.1.2744.7002.150059977302243314164020079415/1.2.276.0.7230010.3.1.3.8323329.18234.1440001306.224430/000000.dcm
 SEG
scratch/scratch/QIN-HEADNECK/QIN-HEADNECK/QIN-HEADNECK-01-0003/1.3.6.1.4.1.14519.5.2.1.2744.7002.150059977302243314164020079415/1.2.276.0.7230010.3.1.3.8323329.18258.1440001306.617246/000000.dcm
 SR
/Users/BillClifford/Downloads/dcmqi-mac/bin/tid1500reader
dcmqi repository URL: https://github.com/qiicr/dcmqi.git revision: f621a32
tag: v1.0.4-47-gf621a32
Number of verifying observers: 0
Activity Session: 1
Reference Segment: 1
SourceSeriesForImageSegmentation:
1.3.6.1.4.1.14519.5.2.1.2744.7002.261560220703676715130542397405
TrackingIdentifier: aorta reference region
  SOPInstanceUID
Backend MacOSX is interactive backend. Turning interactive mode on.
  activitySession
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py",
line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py",
line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/BillClifford/git-home/dcm2tables.test/tabulate.py", line 59,
in <module>
    main()
  File "/Users/BillClifford/git-home/dcm2tables.test/tabulate.py", line 37,
in main
    dicomParser.parse()
  File "/Users/BillClifford/git-home/dcm2tables.test/DICOMParser.py", line
46, in parse
    self.readMeasurements(measurementsJSON)
  File "/Users/BillClifford/git-home/dcm2tables.test/DICOMParser.py", line
289, in readMeasurements
    value = self.dcm.data_element(attr).value
AttributeError: 'NoneType' object has no attribute 'value'

mg.keys() has the key 'ActivitySession'. If I capitalize activitySession in
schema.qdbd it gets past that problem but then fails to find
'TrackingUniqueIdentifier'. The file has a 'Tracking Unique Identifier'
item:

          (fffe,e000) na (Item with undefined length #=4)         # u/l, 1
Item
            (0040,a010) CS [HAS OBS CONTEXT]                        #  16,
1 RelationshipType
            (0040,a040) CS [UIDREF]                                 #   6,
1 ValueType
            (0040,a043) SQ (Sequence with undefined length #=1)     # u/l,
1 ConceptNameCodeSequence
              (fffe,e000) na (Item with undefined length #=3)         #
u/l, 1 Item
                (0008,0100) SH [112040]                                 #
6, 1 CodeValue
                (0008,0102) SH [DCM]                                    #
4, 1 CodingSchemeDesignator
                (0008,0104) LO [Tracking Unique Identifier]             #
 26, 1 CodeMeaning
              (fffe,e00d) na (ItemDelimitationItem)                   #
0, 0 ItemDelimitationItem
            (fffe,e0dd) na (SequenceDelimitationItem)               #   0,
0 SequenceDelimitationItem
            (0040,a124) UI [2.25.318765947155243139724545941675303712684] #
 44, 1 UID
          (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0
ItemDelimitationItem

 but the measurements dictionary does not have something similar:

mg.keys()
[u'ActivitySession', u'ReferencedSegment', u'measurementItems',
u'SourceSeriesForImageSegmentation', u'Finding', u'FindingSite',
u'segmentationSOPInstanceUID', u'TrackingIdentifier']

The measurement dictionary is generated by dcmqi, so Is this a dcmqi bug?

Bill

**Comment by fedorov** [comment]
Bill, so in dcmqi we had a loosely defined convention that CamelCased JSON attributes map directly to the DICOM attributes, and those that start from lower case have a different meaning. However, we did not follow this convention consistently, and also things became more complicated since we have some attributes that do not map to any DICOM concept at all, and we have items that map to the DICOM SR content tree items, and their names are essentially code meanings for the items concept names.... So this is the explanation for lower case.

The problem that you see is because some of the attributes that we need to have exported were added to dcmqi after the release of the binaries you are using. Unfortunately, something got broken in our setup, and we no longer have binaries auto-generated with each new commit (documented in https://github.com/QIICR/dcmqi/issues/260), which is very very annoying ...

Unfortunately, to use the up to date dcmqi, you would either need to build it from source, or use it via docker ... see https://qiicr.gitbooks.io/dcmqi-guide/user_guide/installation.html

**Comment by bcli4d** [comment]
I screwed up... I downloaded and opened the latest source and thought that,
magically, there was already a pre-built dcmqi-mac. I think I mistakenly
reopened the 1.0.5 Mac download.

I'm building the real latest source now.

Sorry for the confusion.

Bill

**Comment by fedorov** [comment]
> I screwed up... I downloaded and opened the latest source and thought that,
magically, there was already a pre-built dcmqi-mac.

No, it is us who screwed up! This is exactly how it is supposed to work - each time there is a new commit, a binary package should be updated for all 3 platforms. And this was working, believe me! But as I noticed few days ago, something got broken, and is not fixed yet ...

**Comment by bcli4d** [comment]
OK. The good news is that I did build dcmqi from source and that fixed the
bug.

Anyway, Sheila has plenty of data for her presentation. So I think we are
good for now. At some point, I'd like to talk again about parsing the
clinical data files. I'm frustrated that I couldn't figure out how to just
walk the file and build a table. I'll be on vacation from Thursday through
4July. Maybe I'll think about it some over that time.

Bill

**Comment by fedorov** [comment]
@bcli4d just noticed as I was looking at the tables you added to the project - you forgot to include `SOPInstanceUID` for the clinical data files! It is the key that ties together all the pieces.

**Comment by bcli4d** [comment]
Hi Andrey,

Thanks for catching that. I'll take care of it.

Bill

**Comment by fedorov** [comment]
Thank you! 

After you update the code, would be super-great if you could also re-run it on the data and update the CSV in our workspace!

**Comment by bcli4d** [comment]
Hi Andrey,

I fixed the missing SOPInstanceUID...I just needed to add it to schema.qdbd.

However, I did a pull from your repo and execution breaks when processing
an SR file. The trace is below.

In summary, it is breaking in ReadPersonObserverName(), which appears to
have been added since late June. The SR file which I am testing against
does not seem to have a Person Observer Name item. So I'm somewhat confused
:-). Are there new versions of the QIN-HEADNECK SR files which have this
field? I did just redownload this same file from TCIA but did not find such
an item in it.

Thanks.

Bill

/Users/BillClifford/Data/QIN-HEADNECK/QIN-HEADNECK-01-0003/1.3.6.1.4.1.14519.5.2.1.2744.7002.150059977302243314164020079415/1.2.276.0.7230010.3.1.3.8323329.18258.1440001306.617246/000000.dcm
Backend MacOSX is interactive backend. Turning interactive mode on.
/Users/BillClifford/local/builds/dcmqi-mac/bin/tid1500reader
dcmqi repository URL: https://github.com/qiicr/dcmqi.git revision: f621a32
tag: v1.0.4-47-gf621a32
Number of verifying observers: 0
Activity Session: 1
Reference Segment: 1
SourceSeriesForImageSegmentation:
1.3.6.1.4.1.14519.5.2.1.2744.7002.261560220703676715130542397405
TrackingIdentifier: aorta reference region
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py",
line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py",
line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/BillClifford/git-home/dcm2tables/tabulate.py", line 61, in
<module>
    main()
  File "/Users/BillClifford/git-home/dcm2tables/tabulate.py", line 39, in
main
    dicomParser.parse()
  File "/Users/BillClifford/git-home/dcm2tables/SRCDParser.py", line 12, in
parse
    super(SRCDParser,self).parse()
  File "/Users/BillClifford/git-home/dcm2tables/DICOMParser.py", line 46,
in parse
    self.readMeasurements(measurementsJSON)
  File "/Users/BillClifford/git-home/dcm2tables/DICOMParser.py", line 300,
in readMeasurements
    value = str(getattr(self, "read%s" % (attr) )())
  File "/Users/BillClifford/git-home/dcm2tables/DICOMParser.py", line 179,
in readPersonObserverName
    return item.PersonName
AttributeError: 'NoneType' object has no attribute 'PersonName'

**Comment by fedorov** [comment]
I don't know how this happened, but apparently this code has not been run on the aorta segmentations. Those segmentations were done using automated processing tools, and that is why they do not have person observer - they instead have a Device Observer Name!

I am working on a fix.

**Comment by fedorov** [comment]
@bcli4d I fixed the missing SOPInstanceUID issue in this commit https://github.com/QIICR/dcm2tables/commit/7f85f7bc684868af15be72612faf9c0a0547cb26, and also fixed the issue you identified above few days ago.

As I am working on the data now, I may come across other issues, so probably it makes sense to hold off re-running the script and re-uploading the tables to the cloud. I will re-run them on a local copy of the DICOM data.

**Comment by bcli4d** [comment]
Got it. Thanks for fixing the missing SOPInstanceUID.

Bill

**Pull request merged**
